name: bern02
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - scikit-learn
  - jupyter
  - jupyterlab
  - ipykernel
  - statsmodels
  - plotly